services:
  adminer:
    image: dockage/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    image: geo-estonia-public-figs
    container_name: app-backend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./kaardirakendus.db:/app/kaardirakendus.db
    env_file:
      - ./.env
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - adminer
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
